services:
  - type: web
    name: muse
    env: docker
    region: frankfurt
    plan: standard
    disk:
      name: data
      mountPath: /data
      sizeGB: 2
    envVars:
    - key: DISCORD_TOKEN
      sync: false
    - key: YOUTUBE_API_KEY
      sync: false
    - key: SPOTIFY_CLIENT_ID
      sync: false
    - key: SPOTIFY_CLIENT_SECRET
      sync: false